name: Backend Smoke

on:
pull_request:
branches: [ main ]
push:
branches: [ main ]
workflow_dispatch: {}

concurrency:
group: backend-smoke-${{ github.ref }}
cancel-in-progress: true

jobs:
smoke:
runs-on: ubuntu-latest
timeout-minutes: 20
env:
PYTHONUNBUFFERED: "1"
GEMINI_OFFLINE: "1"
steps:
- name: Checkout (no LFS)
uses: actions/checkout@v4
with:
lfs: false
fetch-depth: 0

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.11"
      cache: "pip"
      cache-dependency-path: requirements.txt

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Backend smoke test
    run: |
      PYTHONPATH=$GITHUB_WORKSPACE python scripts/smoke_backend.py
